function Hex(e){this.playThrough=0,this.fillColor=[44,62,80],this.tempColor=[44,62,80],this.angularVelocity=0,this.position=0,this.dy=0,this.dt=1,this.sides=6,this.blocks=[],this.angle=180/this.sides,this.targetAngle=this.angle,this.shakes=[],this.sideLength=e,this.strokeColor="blue",this.x=trueCanvas.width/2,this.y=trueCanvas.height/2,this.ct=0,this.lastCombo=this.ct-settings.comboTime,this.lastColorScored="#000",this.comboTime=1,this.texts=[],this.lastRotate=Date.now()
for(var t=0;t<this.sides;t++)this.blocks.push([])
this.shake=function(e){var t=30+60*e.lane
t*=Math.PI/180
var n=Math.cos(t)*e.magnitude,r=Math.sin(t)*e.magnitude
if(gdx-=n,gdy+=r,e.magnitude/=2*this.dt,e.magnitude<1)for(var a=0;a<this.shakes.length;a++)this.shakes[a]==e&&this.shakes.splice(a,1)},this.addBlock=function(e){if(1==gameState||0===gameState){e.settled=1,e.tint=.6
var t=this.sides-e.fallingLane
this.shakes.push({lane:e.fallingLane,magnitude:4.5*(window.devicePixelRatio?window.devicePixelRatio:1)*settings.scale}),t+=this.position,t=(t+this.sides)%this.sides,e.distFromHex=MainHex.sideLength/2*Math.sqrt(3)+e.height*this.blocks[t].length,this.blocks[t].push(e),e.attachedLane=t,e.checked=1}},this.doesBlockCollide=function(e,t,n){if(!e.settled)if(void 0!==t)a=n,0>=t?e.distFromHex-e.iter*this.dt*settings.scale-this.sideLength/2*Math.sqrt(3)<=0?(e.distFromHex=this.sideLength/2*Math.sqrt(3),e.settled=1,e.checked=1):(e.settled=0,e.iter=1.5+waveone.difficulty/15*3):a[t-1].settled&&e.distFromHex-e.iter*this.dt*settings.scale-a[t-1].distFromHex-a[t-1].height<=0?(e.distFromHex=a[t-1].distFromHex+a[t-1].height,e.settled=1,e.checked=1):(e.settled=0,e.iter=1.5+waveone.difficulty/15*3)
else{var r=this.sides-e.fallingLane
r+=this.position,r=(r+this.sides)%this.sides
var a=this.blocks[r]
a.length>0?e.distFromHex+e.iter*this.dt*settings.scale-a[a.length-1].distFromHex-a[a.length-1].height<=0&&(e.distFromHex=a[a.length-1].distFromHex+a[a.length-1].height,this.addBlock(e)):e.distFromHex+e.iter*this.dt*settings.scale-this.sideLength/2*Math.sqrt(3)<=0&&(e.distFromHex=this.sideLength/2*Math.sqrt(3),this.addBlock(e))}},this.rotate=function(e){if((!(Date.now()-this.lastRotate<75)||/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent))&&(1===gameState||0===gameState)){for(this.position+=e,history[this.ct]||(history[this.ct]={}),history[this.ct].rotate?history[this.ct].rotate+=e:history[this.ct].rotate=e;this.position<0;)this.position+=6
this.position=this.position%this.sides,this.blocks.forEach(function(t){t.forEach(function(t){t.targetAngle=t.targetAngle-60*e})}),this.targetAngle=this.targetAngle-60*e,this.lastRotate=Date.now()}},this.draw=function(){this.x=trueCanvas.width/2,-2!=gameState&&(this.y=trueCanvas.height/2),this.sideLength=settings.hexWidth,gdx=0,gdy=0
for(var e=0;e<this.shakes.length;e++)this.shake(this.shakes[e])
this.angle>this.targetAngle?this.angularVelocity-=angularVelocityConst*this.dt:this.angle<this.targetAngle&&(this.angularVelocity+=angularVelocityConst*this.dt),Math.abs(this.angle-this.targetAngle+this.angularVelocity)<=Math.abs(this.angularVelocity)?(this.angle=this.targetAngle,this.angularVelocity=0):this.angle+=this.angularVelocity,drawPolygon(this.x+gdx,this.y+gdy+this.dy,this.sides,this.sideLength,this.angle,arrayToColor(this.fillColor),0,"rgba(0,0,0,0)")}}function arrayToColor(e){return"rgb("+e[0]+","+e[1]+","+e[2]+")"}