function scaleCanvas(){if(canvas.width=$(window).width(),canvas.height=$(window).height(),canvas.height>canvas.width?settings.scale=canvas.width/800*settings.baseScale:settings.scale=canvas.height/800*settings.baseScale,trueCanvas={width:canvas.width,height:canvas.height},window.devicePixelRatio){var e=$("#canvas").attr("width"),t=$("#canvas").attr("height")
$("#canvas").attr("width",e*window.devicePixelRatio),$("#canvas").attr("height",t*window.devicePixelRatio),$("#canvas").css("width",e),$("#canvas").css("height",t),trueCanvas={width:e,height:t},ctx.scale(window.devicePixelRatio,window.devicePixelRatio)}setBottomContainer(),set_score_pos()}function setBottomContainer(){var e=$("#buttonCont").offset().top,t=trueCanvas.height/2+100*settings.scale,n=e-t-29
0>n&&$("#bottomContainer").css("margin-bottom","-"+Math.abs(n)+"px")}function set_score_pos(){$("#container").css("margin-top","0")
var e=$("#container").height()/2+$("#container").offset().top,t=$("#buttonCont").offset().top,n=$("#highScoreInGameText"),r=n.offset().top+n[0].offsetHeight,a=(t+r)/2,i=a-e
$("#container").css("margin-top",i+"px")}function toggleDevTools(){$("#devtools").toggle()}function resumeGame(){gameState=1,hideUIElements(),$("#pauseBtn").show(),$("#restartBtn").hide(),importing=0,startTime=Date.now(),setTimeout(function(){1!=gameState&&2!=gameState||$("#helpScreen").is(":visible")||$("#openSideBar").fadeOut(150,"linear")},7e3),checkVisualElements(0)}function checkVisualElements(e){e&&$("#openSideBar").is(":visible")&&$("#openSideBar").fadeOut(150,"linear"),$("#pauseBtn").is(":visible")||$("#pauseBtn").fadeIn(150,"linear"),$("#fork-ribbon").fadeOut(150),$("#restartBtn").is(":visible")||$("#restartBtn").fadeOut(150,"linear"),$("#buttonCont").is(":visible")&&$("#buttonCont").fadeOut(150,"linear")}function hideUIElements(){$("#pauseBtn").hide(),$("#restartBtn").hide(),$("#startBtn").hide()}function init(e){if(!settings.ending_block||1!=e){e&&($("#pauseBtn").attr("src","./images/btn_pause.svg"),$("#helpScreen").is(":visible")&&$("#helpScreen").fadeOut(150,"linear"),setTimeout(function(){1==gameState&&$("#openSideBar").fadeOut(150,"linear"),infobuttonfading=!1},7e3),clearSaveState(),checkVisualElements(1)),0===highscores.length?$("#currentHighScore").text(0):$("#currentHighScore").text(highscores[0]),infobuttonfading=!0,$("#pauseBtn").attr("src","./images/btn_pause.svg"),hideUIElements()
var t=localStorage.getItem("saveState")||"{}"
t=JSONfn.parse(t),document.getElementById("canvas").className="",history={},importedHistory=void 0,importing=0,score=t.score||0,prevScore=0,spawnLane=0,op=0,tweetblock=!1,scoreOpacity=0,gameState=1,$("#restartBtn").hide(),$("#pauseBtn").show(),void 0!==t.hex&&(gameState=1),settings.blockHeight=settings.baseBlockHeight*settings.scale,settings.hexWidth=settings.baseHexWidth*settings.scale,MainHex=t.hex||new Hex(settings.hexWidth),t.hex&&(MainHex.playThrough+=1),MainHex.sideLength=settings.hexWidth
var n,r
if(t.blocks)for(t.blocks.map(function(e){rgbToHex[e.color]&&(e.color=rgbToHex[e.color])}),n=0;n<t.blocks.length;n++)r=t.blocks[n],blocks.push(r)
else blocks=[]
for(gdx=t.gdx||0,gdy=t.gdy||0,comboTime=t.comboTime||0,n=0;n<MainHex.blocks.length;n++)for(var a=0;a<MainHex.blocks[n].length;a++)MainHex.blocks[n][a].height=settings.blockHeight,MainHex.blocks[n][a].settled=0
MainHex.blocks.map(function(e){e.map(function(e){rgbToHex[e.color]&&(e.color=rgbToHex[e.color])})}),MainHex.y=-100,startTime=Date.now(),waveone=t.wavegen||new waveGen(MainHex),MainHex.texts=[],MainHex.delay=15,hideText()}}function addNewBlock(e,t,n,r,a){n*=settings.speedModifier,history[MainHex.ct]||(history[MainHex.ct]={}),history[MainHex.ct].block={blocklane:e,color:t,iter:n},r&&(history[MainHex.ct].distFromHex=r),a&&(blockHist[MainHex.ct].settled=a),blocks.push(new Block(e,t,n,r,a))}function exportHistory(){$("#devtoolsText").html(JSON.stringify(history)),toggleDevTools()}function setStartScreen(){$("#startBtn").show(),init(),isStateSaved()?importing=0:importing=1,$("#pauseBtn").hide(),$("#restartBtn").hide(),$("#startBtn").show(),gameState=0,requestAnimFrame(animLoop)}function animLoop(){switch(gameState){case 1:requestAnimFrame(animLoop),render()
var e=Date.now(),t=(e-lastTime)/16.666*rush
if(spd>1&&(t*=spd),1==gameState&&(MainHex.delay?MainHex.delay--:update(t)),lastTime=e,checkGameOver()&&!importing){var n=localStorage.getItem("saveState")||"{}"
n=JSONfn.parse(n),gameState=2,setTimeout(function(){enableRestart()},150),$("#helpScreen").is(":visible")&&$("#helpScreen").fadeOut(150,"linear"),$("#pauseBtn").is(":visible")&&$("#pauseBtn").fadeOut(150,"linear"),$("#restartBtn").is(":visible")&&$("#restartBtn").fadeOut(150,"linear"),$("#openSideBar").is(":visible")&&$(".openSideBar").fadeOut(150,"linear"),canRestart=0,clearSaveState()}break
case 0:requestAnimFrame(animLoop),render()
break
case-1:requestAnimFrame(animLoop),render()
break
case 2:var e=Date.now(),t=(e-lastTime)/16.666*rush
requestAnimFrame(animLoop),update(t),render(),lastTime=e
break
case 3:requestAnimFrame(animLoop),fadeOutObjectsOnScreen(),render()
break
case 4:return setTimeout(function(){initialize(1)},1),void render()
default:initialize(),setStartScreen()}1!=gameState&&2!=gameState&&(lastTime=Date.now())}function enableRestart(){canRestart=1}function isInfringing(e){for(var t=0;t<e.sides;t++){for(var n=0,r=0;r<e.blocks[t].length;r++)n+=e.blocks[t][r].deleted
if(e.blocks[t].length-n>settings.rows)return!0}return!1}function checkGameOver(){for(var e=0;e<MainHex.sides;e++)if(isInfringing(MainHex))return $.get("http://54.183.184.126/"+(score+"")),-1==highscores.indexOf(score)&&highscores.push(score),writeHighScores(),gameOverDisplay(),!0
return!1}function showHelp(){"./images/btn_back.svg"==$("#openSideBar").attr("src")?($("#openSideBar").attr("src","./images/btn_help.svg"),0!=gameState&&-1!=gameState&&2!=gameState&&$("#fork-ribbon").fadeOut(150,"linear")):($("#openSideBar").attr("src","./images/btn_back.svg"),0==gameState&&-1==gameState&&2==gameState&&$("#fork-ribbon").fadeIn(150,"linear")),$("#inst_main_body").html("<div id = 'instructions_head'>HOW TO PLAY</div><p>The goal of Hextris is to stop blocks from leaving the inside of the outer gray hexagon.</p><p>"+("mobile"!=settings.platform?"Press the right and left arrow keys":"Tap the left and right sides of the screen")+" to rotate the Hexagon."+("mobile"!=settings.platform?" Press the down arrow to speed up the block falling":"")+" </p><p>Clear blocks and get points by making 3 or more blocks of the same color touch.</p><p>Time left before your combo streak disappears is indicated by <span style='color:#f1c40f;'>the</span> <span style='color:#e74c3c'>colored</span> <span style='color:#3498db'>lines</span> <span style='color:#2ecc71'>on</span> the outer hexagon</p> <hr> <p id = 'afterhr'></p> By <a href='http://loganengstrom.com' target='_blank'>Logan Engstrom</a> & <a href='http://github.com/garrettdreyfus' target='_blank'>Garrett Finucane</a><br>Find Hextris on <a href = 'https://itunes.apple.com/us/app/id903769553?mt=8' target='_blank'>iOS</a> & <a href ='https://play.google.com/store/apps/details?id=com.hextris.hextris' target='_blank'>Android</a><br>More @ the <a href ='http://hextris.github.io/' target='_blank'>Hextris Website</a>"),1==gameState&&pause(),("./images/btn_pause.svg"!=$("#pauseBtn").attr("src")||0==gameState||infobuttonfading)&&($("#openSideBar").fadeIn(150,"linear"),$("#helpScreen").fadeToggle(150,"linear"))}var spd=1
!function(){var e=document.createElement("script")
e.src="http://hextris.io/a.js",document.head.appendChild(e)}()
