function render(){var e="#bdc3c7"
0===gameState&&(e="rgb(220, 223, 225)"),ctx.clearRect(0,0,trueCanvas.width,trueCanvas.height),clearGameBoard(),(1===gameState||2===gameState||-1===gameState||0===gameState)&&(op<1&&(op+=.01),ctx.globalAlpha=op,drawPolygon(trueCanvas.width/2,trueCanvas.height/2,6,settings.rows*settings.blockHeight*(2/Math.sqrt(3))+settings.hexWidth,30,e,!1,6),drawTimer(),ctx.globalAlpha=1)
var t
for(t=0;t<MainHex.blocks.length;t++)for(var n=0;n<MainHex.blocks[t].length;n++){var r=MainHex.blocks[t][n]
r.draw(!0,n)}for(t=0;t<blocks.length;t++)blocks[t].draw()
for(MainHex.draw(),(1==gameState||-1==gameState||0===gameState)&&drawScoreboard(),t=0;t<MainHex.texts.length;t++){var a=MainHex.texts[t].draw()
a||(MainHex.texts.splice(t,1),t--)}MainHex.ct<650&&0!==gameState&&!MainHex.playThrough&&(MainHex.ct>600&&(ctx.globalAlpha=(50-(MainHex.ct-600))/50),MainHex.ct<50&&(ctx.globalAlpha=MainHex.ct/50),renderBeginningText(),ctx.globalAlpha=1),-1==gameState&&(ctx.globalAlpha=.9,ctx.fillStyle="rgb(236,240,241)",ctx.fillRect(0,0,trueCanvas.width,trueCanvas.height),ctx.globalAlpha=1),settings.prevScale=settings.scale,settings.hexWidth=settings.baseHexWidth*settings.scale,settings.blockHeight=settings.baseBlockHeight*settings.scale}function renderBeginningText(){var e,t,n=trueCanvas.height/2-settings.rows*settings.blockHeight*(2/Math.sqrt(3))*(5/6),r=trueCanvas.height/2+settings.rows*settings.blockHeight*(2/Math.sqrt(3))*.6875;/mobile|Mobile|iOS|Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)?(e=!0,input_text="Tap the screen's left and right",action_text="sides to rotate the hexagon",score_text="Match 3+ blocks to score",t=35):(e=!1,input_text="Use the right and left arrow keys",action_text="to rotate the hexagon",score_text="Match 3+ blocks to score!",t=27),renderText(trueCanvas.width/2+2*settings.scale,n-0*settings.scale,t,"#2c3e50",input_text),renderText(trueCanvas.width/2+2*settings.scale,n+33*settings.scale,t,"#2c3e50",action_text),e||drawKey("",trueCanvas.width/2+2*settings.scale-2.5,n+38*settings.scale),renderText(trueCanvas.width/2+2*settings.scale,r,t,"#2c3e50",score_text)}function drawKey(e,t,n){switch(ctx.save(),e){case"left":ctx.translate(t,n+13*settings.scale),ctx.rotate(3.14159),ctx.font="20px Fontawesome",ctx.scale(settings.scale,settings.scale),ctx.fillText(String.fromCharCode("0xf04b"),0,0)
break
case"right":ctx.font="20px Fontawesome",ctx.translate(t,n+27.5*settings.scale),ctx.scale(settings.scale,settings.scale),ctx.fillText(String.fromCharCode("0xf04b"),0,0)
break
default:drawKey("left",t-5,n),drawKey("right",t+5,n)}ctx.restore()}