function easeOutCubic(e,t,n,r){return n*((e=e/r-1)*e*e+1)+t}function renderText(e,t,n,r,a,i){if(ctx.save(),!i)var i="20px Exo"
n*=settings.scale,ctx.font=n+i,ctx.textAlign="center",ctx.fillStyle=r,ctx.fillText(a,e,t+n/2-9*settings.scale),ctx.restore()}function drawScoreboard(){scoreOpacity<1&&(scoreOpacity+=.01,textOpacity+=.01),ctx.globalAlpha=textOpacity
var e=50,t=score+""
6==t.length?e=43:7==t.length?e=35:8==t.length?e=31:9==t.length&&(e=27)
var n="rgb(236, 240, 241)",r="mobile"==settings.platform?35:30,a=trueCanvas.height/2+gdy+100*settings.scale
0===gameState?(renderText(trueCanvas.width/2+gdx+6*settings.scale,trueCanvas.height/2+gdy,60,"rgb(236, 240, 241)",String.fromCharCode("0xf04b"),"px FontAwesome"),renderText(trueCanvas.width/2+gdx+6*settings.scale,trueCanvas.height/2.1+gdy-155*settings.scale,150,"#2c3e50","Hextris"),renderText(trueCanvas.width/2+gdx+5*settings.scale,a+10,r,"rgb(44,62,80)","Play!")):0!=gameState&&textOpacity>0?(textOpacity-=.05,renderText(trueCanvas.width/2+gdx+6*settings.scale,trueCanvas.height/2+gdy,60,"rgb(236, 240, 241)",String.fromCharCode("0xf04b"),"px FontAwesome"),renderText(trueCanvas.width/2+gdx+6*settings.scale,trueCanvas.height/2+gdy-155*settings.scale,150,"#2c3e50","Hextris"),renderText(trueCanvas.width/2+gdx+5*settings.scale,a,r,"rgb(44,62,80)","Play!"),ctx.globalAlpha=scoreOpacity,renderText(trueCanvas.width/2+gdx,trueCanvas.height/2+gdy,e,n,score)):(ctx.globalAlpha=scoreOpacity,renderText(trueCanvas.width/2+gdx,trueCanvas.height/2+gdy,e,n,score)),ctx.globalAlpha=1}function clearGameBoard(){drawPolygon(trueCanvas.width/2,trueCanvas.height/2,6,trueCanvas.width/2,30,hexagonBackgroundColor,0,"rgba(0,0,0,0)")}function drawPolygon(e,t,n,r,a,i,s,o){ctx.fillStyle=i,ctx.lineWidth=s,ctx.strokeStyle=o,ctx.beginPath()
var u=rotatePoint(0,r,a)
ctx.moveTo(u.x+e,u.y+t)
for(var l=u.x,c=u.y,h=0;n>h;h++)u=rotatePoint(l,c,360/n),ctx.lineTo(u.x+e,u.y+t),l=u.x,c=u.y
ctx.closePath(),ctx.fill(),ctx.stroke(),ctx.strokeStyle="rgba(0,0,0,0)"}function toggleClass(e,t){$(e).hasClass(t)?$(e).removeClass(t):$(e).addClass(t)}function showText(e){var t={paused:"<div class='centeredHeader unselectable'>Game Paused</div>",pausedAndroid:"<div class='centeredHeader unselectable'>Game Paused</div><div class='unselectable centeredSubHeader' style='position:absolute;margin-left:-150px;left:50%;margin-top:20px;width:300px;font-size:16px;'><a href = 'https://play.google.com/store/apps/details?id=com.hextris.hextrisadfree' target='_blank'Want to support the developers? Don't like ads? Tap for Hextris ad-free!</a></div>",pausediOS:"<div class='centeredHeader unselectable'>Game Paused</div><div class='unselectable centeredSubHeader' style='position:absolute;margin-left:-150px;left:50%;margin-top:20px;width:300px;font-size:16px;'><a href = 'https://itunes.apple.com/us/app/hextris-ad-free/id912895524?mt=8' target='_blank'>Want to support the developers? Don't like ads? Tap for Hextris ad-free!</a></div>",pausedOther:"<div class='centeredHeader unselectable'>Game Paused</div><div class='unselectable centeredSubHeader' style='margin-top:10px;position:absolute;left:50%;margin-left:-190px;max-width:380px;font-size:18px;'><a href = 'http://hextris.github.io/' target='_blank'>Want to support the developers? Click here to buy one of the ad-free mobile versions!</a></div>",start:"<div class='centeredHeader unselectable' style='line-height:80px;'>Press enter to start</div>"}
"paused"==e&&("android"==settings.os?e="pausedAndroid":"ios"==settings.os?e="pausediOS":"nonmobile"==settings.platform&&(e="pausedOther")),"gameover"==e&&$("#gameoverscreen").fadeIn(),$(".overlay").html(t[e]),$(".overlay").fadeIn("1000","swing")}function setMainMenu(){gameState=4,canRestart=!1,setTimeout(function(){canRestart="s"},500),$("#restartBtn").hide(),"btn_pause.svg"==$("#pauseBtn").replace(/^.*[\\\/]/,"")?$("#pauseBtn").attr("src","./images/btn_resume.svg"):$("#pauseBtn").attr("src","./images/btn_pause.svg")}function hideText(){$(".overlay").fadeOut(150,function(){$(".overlay").html("")})}function gameOverDisplay(){settings.ending_block=!1,Cookies.set("visited",!0)
var e=document.getElementById("canvas")
e.className="blur",updateHighScores(),0===highscores.length?$("#currentHighScore").text(0):$("#currentHighScore").text(highscores[0]),$("#gameoverscreen").fadeIn(),$("#buttonCont").fadeIn(),$("#container").fadeIn(),$("#socialShare").fadeIn(),$("#restart").fadeIn(),set_score_pos()}function updateHighScores(){$("#cScore").text(score),$("#1place").text(highscores[0]),$("#2place").text(highscores[1]),$("#3place").text(highscores[2])}function pause(e){if(0!=gameState&&2!=gameState&&pausable){pausable=!1,writeHighScores()
var t
t=e?"":"paused"
document.getElementById("canvas");-1==gameState?($("#fork-ribbon").fadeOut(300,"linear"),$("#restartBtn").fadeOut(300,"linear"),$("#buttonCont").fadeOut(300,"linear"),$("#helpScreen").is(":visible")&&$("#helpScreen").fadeOut(300,"linear"),$("#pauseBtn").attr("src","./images/btn_pause.svg"),$(".helpText").fadeOut(300,"linear"),$("#overlay").fadeOut(300,"linear"),hideText(),setTimeout(function(){gameState=prevGameState,pausable=!0},400)):-2!=gameState&&0!==gameState&&2!==gameState&&($("#restartBtn").fadeIn(300,"linear"),$("#buttonCont").fadeIn(300,"linear"),$(".helpText").fadeIn(300,"linear"),"paused"==t&&showText(t),$("#fork-ribbon").fadeIn(300,"linear"),$("#pauseBtn").attr("src","./images/btn_resume.svg"),$("#overlay").fadeIn(300,"linear"),prevGameState=gameState,setTimeout(function(){pausable=!0},400),gameState=-1)}}var pausable=!0
